import React from "react";
import type { Metadata } from "next";
import Animate_Loginform from "../../components/ui/animation/Animate_Loginform";

export const metadata: Metadata = {
  title: "login Page",
  description: "Generated by create next app",
};
interface AuthLayoutProps {
  children: React.ReactNode;
}

const layout = ({ children }: AuthLayoutProps) => {
  return (
    <div className="fullscreen scale-0" id="loginForms">
      {children}
      <Animate_Loginform />
    </div>
  );
};

export default layout;
